import type { Kitten } from "./types";

export const kittens: Kitten[] = [
  {
    id: "atl-001",
    name: "Misty",
    dob: "2026-03-10",
    sex: "female",
    color: "Blue",
    pattern: "Solid",
    priceUSD: 2800,
    priceCAD: 3800,
    location: "atlanta",
    status: "available",
    photos: ["/images/cats/placeholder.svg"],
    sire: "Lord Ashton",
    dam: "Duchess Willow",
    personality:
      "Misty is a gentle soul who loves to curl up on your lap. She greets everyone with a soft chirp and enjoys watching birds from the windowsill.",
    registeredName: "Jiliang's Misty Morning",
  },
  {
    id: "atl-002",
    name: "Winston",
    dob: "2026-03-10",
    sex: "male",
    color: "Lilac",
    pattern: "Solid",
    priceUSD: 3000,
    priceCAD: 4000,
    location: "atlanta",
    status: "available",
    photos: ["/images/cats/placeholder.svg"],
    sire: "Lord Ashton",
    dam: "Duchess Willow",
    personality:
      "Winston is a confident, outgoing boy with a big personality. He loves interactive toys and will follow you from room to room.",
    registeredName: "Jiliang's Sir Winston",
  },
  {
    id: "atl-003",
    name: "Cleo",
    dob: "2026-02-15",
    sex: "female",
    color: "Cinnamon",
    pattern: "Solid",
    priceUSD: 3200,
    priceCAD: 4300,
    location: "atlanta",
    status: "reserved",
    photos: ["/images/cats/placeholder.svg"],
    sire: "Lord Ashton",
    dam: "Lady Primrose",
    personality:
      "Cleo is an affectionate girl with a playful streak. She loves to be held and will purr the moment you pick her up.",
    registeredName: "Jiliang's Cleopatra",
  },
  {
    id: "atl-004",
    name: "Oliver",
    dob: "2026-01-20",
    sex: "male",
    color: "Blue",
    pattern: "Solid",
    priceUSD: 2800,
    priceCAD: 3800,
    location: "atlanta",
    status: "adopted",
    photos: ["/images/cats/placeholder.svg"],
    sire: "Lord Ashton",
    dam: "Duchess Willow",
    personality:
      "Oliver is a laid-back gentleman who enjoys lounging in sunbeams. He gets along wonderfully with children and other pets.",
    registeredName: "Jiliang's Oliver Twist",
  },
  {
    id: "tor-001",
    name: "Maple",
    dob: "2026-03-22",
    sex: "female",
    color: "Golden Shaded",
    pattern: "Shaded",
    priceUSD: 3200,
    priceCAD: 4200,
    location: "toronto",
    status: "available",
    photos: ["/images/cats/placeholder.svg"],
    sire: "Grand Duke Sterling",
    dam: "Belle of Toronto",
    personality:
      "Maple is a curious explorer with stunning golden fur. She loves discovering new corners of the house and playing with crinkle toys.",
    registeredName: "Jiliang's Golden Maple",
  },
  {
    id: "tor-002",
    name: "Chester",
    dob: "2026-03-22",
    sex: "male",
    color: "Chocolate",
    pattern: "Solid",
    priceUSD: 3000,
    priceCAD: 4000,
    location: "toronto",
    status: "available",
    photos: ["/images/cats/placeholder.svg"],
    sire: "Grand Duke Sterling",
    dam: "Belle of Toronto",
    personality:
      "Chester is a sweet, easygoing boy with a rich chocolate coat. He loves chin scratches and will knead biscuits on your favorite blanket.",
    registeredName: "Jiliang's Chester",
  },
  {
    id: "tor-003",
    name: "Ivy",
    dob: "2026-02-28",
    sex: "female",
    color: "Lilac",
    pattern: "Solid",
    priceUSD: 3000,
    priceCAD: 4000,
    location: "toronto",
    status: "reserved",
    photos: ["/images/cats/placeholder.svg"],
    sire: "Grand Duke Sterling",
    dam: "Countess Aurora",
    personality:
      "Ivy is a dainty, elegant girl who carries herself with quiet confidence. She enjoys gentle play sessions and cozy naps by the fireplace.",
    registeredName: "Jiliang's Ivy League",
  },
  {
    id: "tor-004",
    name: "Hugo",
    dob: "2026-01-05",
    sex: "male",
    color: "Blue",
    pattern: "Solid",
    priceUSD: 2800,
    priceCAD: 3800,
    location: "toronto",
    status: "adopted",
    photos: ["/images/cats/placeholder.svg"],
    sire: "Grand Duke Sterling",
    dam: "Belle of Toronto",
    personality:
      "Hugo is a robust, friendly boy who loves everyone he meets. He adjusted instantly to his new family and is thriving in his forever home.",
    registeredName: "Jiliang's Hugo Boss",
  },
];
